# FROM node:14-alpine
FROM --platform=linux/x86_64 node:18.19.0-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    locales \
    && rm -rf /var/lib/apt/lists/* \
    && sed -i -e 's/# ja_JP.UTF-8 UTF-8/ja_JP.UTF-8 UTF-8/' /etc/locale.gen \
    && locale-gen \
    && update-locale LANG=ja_JP.UTF-8

ENV LANG ja_JP.UTF-8
ENV LC_ALL ja_JP.UTF-8

COPY frontend/package*.json ./
RUN rm -rf node_modules
RUN npm ci
RUN npm install

COPY frontend .

EXPOSE 3000

CMD ["npm", "start"]